title: 'MostlyWhat Systems'
default_lang: en
author:
  name: MostlyWhat
  email: admin@mostlywhat.com
taxonomies:
  - category
  - tag
metadata:
  description: 'MostlyWhat Systems'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
